version: 2
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    branches:
      only:
        - master
    working_directory: ~/gotenks
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy to Github Pages
          command: yarn deploy
