version: 2
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    branches:
      only:
        - master
    working_directory: ~/gotenks
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build for deployment
          command: yarn build
      - run:
          name: clone the deployment repo
          working_directory: ~/gotenks
          command: git clone --depth 1 git@github.com:nimish-gupta/nimish-gupta.github.io.git
      - run:
          name: clear old deployment files
          command: rm -rf nimish-gupta.github.io/*
      - run:
          name: copy new build
          command: cp -vr build/* nimish-gupta.github.io
      - deploy:
          name: Deploy new build
          working_directory: ~/gotenks/nimish-gupta.github.io
          command: |
            git add .
            git config credential.helper 'cache --timeout=120'
            git config user.email "nimishgupta18396@gmail.com"
            git config user.name "Nimish Gupta"
            git commit --allow-empty -m "Deployed From Circle CI on `date`"
            git push -q https://${DEPLOY_KEY}@github.com:nimish-gupta/nimish-gupta.github.io.git master
